## backup-minio-config.yaml
## * https://dgraph.io/docs/master/enterprise-features/binary-backups/
backups:
  admin:
    password: whiterabbit
  ## Minio Access/Secret Keys fictitious and for demonstration purposes only.
  keys:
    minio: 
      access: mycompanydgraphbackups
      sedret: aBcDeFgHiJkLmNoPqRsTuVwXyZ/+0124567890AbCdEfGhIjKlMnOpQrStUvWxYz+/01234567890aBcDeFgHi==
alpha:
  acl:
    file:
      ## Demonstration Purposes Only: 1234567890123456789012345678901
      ## Note that Kubernetes secrets must be base64-encoded
      hmac_secret_file: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMQo=
