## NOTE: TLS Encryption for Zero is only available in v20.11.0+
alpha:
  tls:
    files:
      ## Note that Kubernetes secrets must be base64-encoded
      ca.crt: REDACTED
      ca.key: REDACTED
      client.internaluser.crt: REDACTED
      client.internaluser.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
zero:
  tls:
    files:
      ## Note that Kubernetes secrets must be base64-encoded
      ca.crt: REDACTED
      ca.key: REDACTED
      client.internaluser.crt: REDACTED
      client.internaluser.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
