## Specify TLS configuration options for `dgraph alpha` and `dgraph zero`
## * https://dgraph.io/docs/v20.11/deploy/tls-configuration/#using-tls-with-internal-and-external-ports-encrypted
## NOTE: TLS Encryption for Zero is only available in v20.11.0+
## NOTE: Client Certificates used for Mutual TLS must be included, as these are
## need by Dgraph nodes to authenticate to each other.


with Dgraph Alpha do not need to
## be included in this file.  These client certificates are needed by clients to
## access Dgraph Alpha when tls_client_auth is set to REQUIREANDVERIFY
alpha:
  tls:
    files:
      ## Note that Kubernetes secrets must be base64-encoded
      ca.crt: REDACTED
      ca.key: REDACTED
      client.internaluser.crt: REDACTED
      client.internaluser.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
zero:
  tls:
    files:
      ## Note that Kubernetes secrets must be base64-encoded
      ca.crt: REDACTED
      ca.key: REDACTED
      client.internaluser.crt: REDACTED
      client.internaluser.key: REDACTED
      node.crt: REDACTED
      node.key: REDACTED
