releases:
  - name: dev
    namespace: default
    chart: {{ env "PWD" }}/charts/dgraph
    values:
      - alpha:
          extraEnvs:
            - name: DGRAPH_ALPHA_GRAPHQL_LAMBDA_URL
              value: http://lambda-dgraph-lambda.default.svc:8686/graphql-worker
            - name: DGRAPH_ALPHA_WHITELIST
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

  - name: lambda
    chart: {{ env "PWD" }}/charts/dgraph-lambda
    values:
      - env:
        - name: DGRAPH_URL
          value: http://dev-dgraph-alpha-headless.default.svc:8080
