## backup-minio-config.yaml
## * https://dgraph.io/docs/master/enterprise-features/binary-backups/
backups:
  full:
    enabled: true
    schedule: 0 * * * *
    destination: minio://my-release-minio.default.svc:9000/dgraph-backups
  incremental:
    enabled: true
    schedule: 0 1-23 * * *
    destination: minio://my-release-minio.default.svc:9000/dgraph-backups
  admin:
    user: alice
alpha:
  acl:
    enabled: true
  configFile:
    config.hcl: |
      "acl_secret_file" = "/dgraph/acl/hmac_secret_file"
      "whitelist" = "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,172.20.0.0/12"
      "lru_mb" = 2048
  extraEnvs:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: minio123
