# ingress-nginx with certificate manager
# * https://cert-manager.io/
# * https://kubernetes.github.io/ingress-nginx/
global:
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
    - hosts:
      - ratel.example.com
      - alpha.example.com
      secretName: example-tls
    ratel_hostname: ratel.example.com
    alpha_hostname: alpha.example.com
