{{ if .Values.zero.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dgraph.zero.fullname" . }}-config
  namespace: {{ include "dgraph.namespace" . }}
  labels:
    app.kubernetes.io/component: {{ .Values.zero.name }}
    component: {{ .Values.zero.name }}
    {{- include "dgraph.standardLabels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.zero.configFile }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{ end }}
