{{ if and .Values.zero.tls.enabled .Values.zero.tls.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dgraph.zero.fullname" . }}-tls-secret
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.zero.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.zero.tls.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.zero.tls.files }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{ end }}
