apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.zero.fullname" . }}-headless
  namespace: {{ include "dgraph.namespace" . }}
  labels:
    app.kubernetes.io/component: {{ .Values.zero.name }}
    component: {{ .Values.zero.name }}
    {{- include "dgraph.standardLabels" . | nindent 4 }}
    {{- with .Values.zero.serviceHeadless.labels }}
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc-zero
      port: 5080
      targetPort: 5080
  selector:
    app: {{ template "dgraph.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.zero.name }}
  publishNotReadyAddresses: {{ .Values.zero.service.publishNotReadyAddresses }}
