{{- if and (or .Values.backups.full.enabled .Values.backups.incremental.enabled) .Values.backups.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "dgraph.backups.fullname" . }}-fileserver
  namespace: {{ include "dgraph.namespace" . }}
  labels:
    component: {{ .Values.backups.name }}
    app.kubernetes.io/component: {{ .Values.backups.name }}
    {{- include "dgraph.standardLabels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.backups.nfs.storage }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.backups.nfs.path }}
    server: {{ .Values.backups.nfs.server }}
{{- end }}
