{{- if and (or .Values.backups.full.enabled .Values.backups.incremental.enabled) .Values.backups.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "dgraph.backups.fullname" . }}-claim
  namespace: {{ include "dgraph.namespace" . }}
  labels:
    component: {{ .Values.backups.name }}
    app.kubernetes.io/component: {{ .Values.backups.name }}
    {{- include "dgraph.standardLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: {{ template "dgraph.backups.fullname" . }}-fileserver
  resources:
    requests:
      storage: {{ .Values.backups.nfs.storage }}
{{- end }}
