## Lambda Example

releases:
  - name: dev
    namespace: default
    chart: {{ env "PWD" }}/../../charts/dgraph
    values:
      - alpha:
          extraEnvs:
            ## NOTE: The url is formatted as:
            ##  - http://<helm-chart-release-name>-dgraph-lambda.<namespace>.svc/graphql-worker
            ## NOTE: Configuration env vars have changed in v21.03.
            ## Use appropriate value for the dgraph version used.
            - name: DGRAPH_ALPHA_GRAPHQL
              value: lambda-url=http://lambda-dgraph-lambda.default.svc/graphql-worker
  - name: lambda
    namespace: default
    chart: {{ env "PWD" }}/../../charts/dgraph-lambda
    values:
      - ./example/script.yaml
      - env:
        - name: DGRAPH_URL
          ## http://<helm-chart-release-name>-dgraph-alpha-headless.<namespace>.svc:8080
          value: http://dev-dgraph-alpha-headless.default.svc:8080
