{{ if and .Values.alpha.acl.enabled .Values.alpha.acl.file }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}-acl-secret
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.alpha.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.alpha.tls.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.alpha.acl.file }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{ end }}
