{{ if and .Values.alpha.encryption.enabled .Values.alpha.encryption.file }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}-encryption-secret
  namespace: {{ include "dgraph.namespace" . }}
  labels:
    {{- include "dgraph.labels" (dict "ctx" . "component" .Values.alpha.name) | nindent 4 }}
type: Opaque
data:
  {{- with .Values.alpha.encryption.file }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{ end }}
