#!/usr/bin/env bash
# Check one development dependency, installing it when AUTO_INSTALL=true.
# Usage: scripts/deps.sh <brew|helm|ct|yamllint|yamale|pre-commit|hook>
set -euo pipefail

tool="${1:?usage: scripts/deps.sh <tool>}"
auto_install="${AUTO_INSTALL:-false}"
ct_version="${CT_VERSION:-3.14.0}"

case "$(uname -s)" in
  Darwin)
    pm=brew
    # Each make step is a new process, so find a Homebrew installed earlier in this run.
    if ! command -v brew >/dev/null 2>&1; then
      for prefix in /opt/homebrew /usr/local; do
        if [ -x "$prefix/bin/brew" ]; then eval "$("$prefix/bin/brew" shellenv)"; fi
      done
    fi
    ;;
  Linux)
    if command -v apt-get >/dev/null 2>&1; then pm=apt
    elif command -v pacman >/dev/null 2>&1; then pm=pacman
    elif command -v dnf >/dev/null 2>&1; then pm=dnf
    elif command -v yum >/dev/null 2>&1; then pm=yum
    else
      echo "Error: no supported package manager found (apt, pacman, dnf, yum)."
      echo ""
      echo "  Install helm, chart-testing (ct), yamllint, yamale, and pre-commit by hand."
      exit 1
    fi
    ;;
  *)
    echo "Error: unsupported OS $(uname -s). Supported: macOS and Linux."
    exit 1
    ;;
esac

# Red Hat rebuilds (Rocky, Alma, CentOS) ship yamllint, pipx, and pre-commit only in EPEL.
epel=""
if [ "$pm" = dnf ] || [ "$pm" = yum ]; then
  if [ -r /etc/os-release ] && grep -qE '^ID_LIKE=.*rhel' /etc/os-release; then
    epel="epel-release"
  fi
fi

sudo=""
if [ "$pm" != brew ] && [ "$(id -u)" -ne 0 ]; then
  sudo="sudo "
fi

# The command that installs packages with this machine's package manager.
pkg_cmd() {
  case "$pm" in
    brew) echo "brew install $*" ;;
    apt) echo "${sudo}apt-get update && ${sudo}apt-get install -y $*" ;;
    pacman) echo "${sudo}pacman -S --needed --noconfirm $*" ;;
    dnf | yum)
      if [ -n "$epel" ]; then
        echo "${sudo}$pm install -y $epel && ${sudo}$pm install -y $*"
      else
        echo "${sudo}$pm install -y $*"
      fi
      ;;
  esac
}

pipx_pkg() {
  case "$pm" in
    pacman) echo python-pipx ;;
    *) echo pipx ;;
  esac
}

# Install the named commands' packages first, but only those not already present.
with_cmds() {
  local missing=() c
  for c in "$@"; do
    command -v "$c" >/dev/null 2>&1 || missing+=("$c")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    echo "$(pkg_cmd "${missing[@]}") && "
  fi
}

ct_arch() {
  case "$(uname -m)" in
    x86_64 | amd64) echo amd64 ;;
    aarch64 | arm64) echo arm64 ;;
    *) uname -m ;;
  esac
}

# The command that installs $tool on this machine, printed for manual use and run by AUTO_INSTALL.
install_cmd() {
  case "$tool:$pm" in
    helm:brew | helm:pacman) pkg_cmd helm ;;
    helm:*) echo "$(with_cmds curl tar openssl)curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash" ;;
    ct:brew) pkg_cmd chart-testing ;;
    ct:*)
      local url
      url="https://github.com/helm/chart-testing/releases/download/v${ct_version}/chart-testing_${ct_version}_linux_$(ct_arch).tar.gz"
      echo "$(with_cmds curl tar)mkdir -p \"\$HOME/.local/bin\" \"\$HOME/.ct\" && curl -fsSL $url | tar -xz -C \"\$HOME/.ct\" && mv \"\$HOME/.ct/ct\" \"\$HOME/.local/bin/ct\" && mv \"\$HOME/.ct/etc/\"* \"\$HOME/.ct/\""
      ;;
    yamllint:*) pkg_cmd yamllint ;;
    yamale:brew) pkg_cmd yamale ;;
    yamale:*) echo "$(pkg_cmd "$(pipx_pkg)") && pipx install yamale" ;;
    pre-commit:*)
      # EPEL's pre-commit package needs the CRB repository; pipx avoids enabling it.
      if [ "$pm" = yum ] || [ -n "$epel" ]; then
        echo "$(pkg_cmd "$(pipx_pkg)") && pipx install pre-commit"
      else
        pkg_cmd pre-commit
      fi
      ;;
    hook:*) echo "pre-commit install" ;;
    brew:*)
      # Without a terminal the installer cannot prompt, so it must run non-interactively.
      local noninteractive=""
      [ -t 0 ] || noninteractive="NONINTERACTIVE=1 "
      # shellcheck disable=SC2016 # expanded when the command runs
      echo "${noninteractive}"'/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
      ;;
  esac
}

present() {
  case "$tool" in
    hook)
      local hook
      hook="$(git rev-parse --git-path hooks)/pre-commit"
      [ -f "$hook" ] && grep -q "File generated by pre-commit" "$hook"
      ;;
    *) command -v "$tool" >/dev/null 2>&1 ;;
  esac
}

describe() {
  case "$tool" in
    hook) echo "pre-commit hook installed" ;;
    helm) echo "helm $(helm version --short 2>/dev/null)" ;;
    ct) echo "ct $(ct version 2>/dev/null | awk '/^Version/ {print $2}')" ;;
    yamllint) yamllint --version ;;
    yamale) echo "yamale $(command -v yamale)" ;;
    pre-commit) pre-commit --version ;;
    brew) echo "brew $(brew --version | head -1 | awk '{print $2}')" ;;
  esac
}

missing_label() {
  case "$tool" in
    hook) echo "the pre-commit hook is not installed" ;;
    ct) echo "ct (chart-testing) is not installed" ;;
    brew) echo "Homebrew is not installed" ;;
    *) echo "$tool is not installed" ;;
  esac
}

if present; then
  echo "ok: $(describe)"
  exit 0
fi

cmd="$(install_cmd)"

if [ "$auto_install" != "true" ]; then
  echo "Error: $(missing_label)."
  echo ""
  echo "  $cmd"
  echo ""
  echo "  Or re-run with AUTO_INSTALL=true to install automatically."
  exit 1
fi

echo "$tool: not found, installing ..."
bash -c "$cmd"

if [ "$tool" = brew ]; then
  for prefix in /opt/homebrew /usr/local; do
    if [ -x "$prefix/bin/brew" ]; then eval "$("$prefix/bin/brew" shellenv)"; fi
  done
fi

if ! present; then
  echo "Error: $tool installed but is not on PATH."
  echo ""
  echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  exit 1
fi

echo "ok: $(describe)"
