{{- if .Values.alpha.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.alpha.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.alpha.ingress.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.alpha.ingress.tls }}
  tls:
  {{- range .Values.alpha.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.alpha.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "dgraph.alpha.fullname" . }}
              servicePort: 8080
{{- end }}
