{{- /* Determine Backup is REST or GraphQL */}}
{{- define "backup_api_type" -}}
{{- $apiType := "graphql" -}}
{{- $safeVersion := include "dgraph.version" . -}}
{{- if semverCompare "< 20.0" $safeVersion -}}
  {{- $apiType = "rest" -}}
{{- end -}}
{{- printf "%s" $apiType -}}
{{- end -}}
{{- if eq .Values.backups.full.enabled true -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "dgraph.alpha.fullname" . }}-backup-full
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.alpha.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.backups.full.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ template "dgraph.fullname" . }}-backup-full
            image: {{ template "backup.image" . }}
            imagePullPolicy: {{ .Values.backups.image.pullPolicy | quote }}
            command:
             - /usr/bin/bash
             - "-c"
             - |
                set -ex
                source /scripts/backup.sh

                ## Use Single Alpha in Cluster to avoid potential issues with concurrent backups
                ## ref https://discuss.dgraph.io/t/concurrent-backups-can-lead-to-issues/9934/2
                ALPHA_HOST={{ template "dgraph.alpha.fullname" . }}-0.{{ template "dgraph.alpha.fullname" . }}-headless.${POD_NAMESPACE}.svc
                BACKUP_DESTINATION={{ .Values.backups.full.destination }}
                API_TYPE={{ template "backup_api_type" . }}
                MINIO_SECURE={{ .Values.backups.full.minioSecure }}

                ## TODO: check acl, secrests, token
                ## TODO: tls and tls w/ client
                
                FORCE_FULL=true backup
            volumeMounts:
            - name: config-volume
              mountPath: /scripts
            {{- if .Values.alpha.tls.enabled }}
            - name: tls-volume
              mountPath: /dgraph/tls
            {{- end }}
            env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: OnFailure
          volumes:
          - name: config-volume
            configMap:
              name: {{ template "dgraph.fullname" . }}-backup-config
          {{- if .Values.alpha.tls.enabled }}
          - name: tls-volume
            secret:
              secretName: {{ template "dgraph.alpha.fullname" . }}-secret
          {{- end }}     
{{- end }}
