{{- if or (eq .Values.backups.full.enabled true) (eq .Values.backups.incremental.enabled true) (eq .Values.alpha.acl.enabled true) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dgraph.backups.fullname" . }}-secret
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.backups.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.alpha.tls.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
type: Opaque
data:
  backup_admin_password: {{ .Values.backups.admin.password | b64enc | quote }}
{{- end }}
