{{ if .Values.zero.config_file }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dgraph.zero.fullname" . }}-config
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.zero.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- with .Values.zero.config_file }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{ end }}
