{{- if and (eq .Values.ratel.ingress.enabled true) (eq .Values.global.ingress.enabled false) (eq .Values.ratel.enabled true) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "dgraph.ratel.fullname" . }}-ingress
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.ratel.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ratel.ingress.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ratel.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ratel.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ratel.ingress.tls }}
  tls:
  {{- range .Values.ratel.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ratel.ingress.hostname }}
      http:
        paths:
          - backend:
              service:
                name:  {{ template "dgraph.ratel.fullname" . }}
                port:
                 number: 80
            pathType: ImplementationSpecific
            {{- if index $.Values.ratel.ingress "annotations" }}
            {{- if eq (index $.Values.ratel.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb" "nsx" }}
            path: /*
            {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
            path: /
            {{- end }}
            {{- else}}{{/* Has no annotations */}}
            path: /
            {{- end }}
{{- end }}
