{{- /* Generate ingress path */}}
{{- define "path" -}}
  {{- $path := "/" -}}
  {{- if .Values.global.ingress.ingressClassName -}}
    {{- if eq .Values.global.ingress.ingressClassName "gce" "alb" "nsx" }}
      {{- $path = "/*" -}}
    {{- else }}
      {{- $path = "/" -}}
    {{- end }}
  {{- else if index $.Values.global.ingress "annotations" -}}
    {{- if eq (index $.Values.global.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb" "nsx" }}
      {{- $path = "/*" -}}
    {{- else }}
      {{- $path = "/" -}}
    {{- end }}
  {{- end -}}
  {{- printf "%s" $path -}}
{{- end -}}
{{- /* Ratel ingress resource */}}
{{- if and (eq .Values.ratel.ingress.enabled true) (eq .Values.global.ingress.enabled false) (eq .Values.ratel.enabled true) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "dgraph.ratel.fullname" . }}-ingress
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.ratel.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ratel.ingress.annotations }}
  annotations:
    {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ratel.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ratel.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ratel.ingress.tls }}
  tls:
  {{- range .Values.ratel.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name:  {{ template "dgraph.ratel.fullname" . }}
                port:
                 number: 80
            pathType: ImplementationSpecific
            path: {{ template "path" . }}
      {{- if .Values.ratel.ingress.hostname }}
      host: {{ .Values.ratel.ingress.hostname }}
      {{- end }}
{{- end }}
